### ISSUE TITLE
Write issues for describing use cases and improvements as discussed on summit Oct 2022

### ISSUE THREAD

**Issue by e-backmark-ericsson** [eiffel-community/community#144]
During the Eiffel Summit in October 2022 we discussed the following, which should get new (or updated existing) issues

Document potential Use cases (probably under "Usage Examples"):
- [x] How to use Eiffel to calculate DORA metrics (https://github.com/eiffel-community/eiffel/issues/338)
- [x] SBOM - how to create them from Eiffel events, or how to reference externally stored SBOM from Eiffel events(https://github.com/eiffel-community/eiffel/issues/360)
- [x]  Trace vulnerabilities - a vulnerability found upstream; how can I trace what artifacts/deliveries it has been affecting?(https://github.com/eiffel-community/eiffel/issues/361)

Improvements
- [x] Environment - server/services. How to describe a group of servers/services (depends on ArtifactDeployedEvent PR)(https://github.com/eiffel-community/eiffel/issues/362)
- [x] Activity vs Traceability/Artifacts dimension/domain (https://github.com/eiffel-community/eiffel/issues/363)
- [x] Dependencies - relationships between artifacts and between source changes(https://github.com/eiffel-community/eiffel/issues/364)

**Comment by m-linner-ericsson** [comment]
Written Issues for all of the items. Closing this
